language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:   #Optional 
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

    android:
    update_sdk: true  #Check for the updates each time you run the build.
    components:
        - platform-tools
        - tools
        - build-tools-25.0.0    #Build tool version
        - android-25            #targate api version

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api

script:
    - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    - ./gradlew 