language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-16
    - android-21
    - android-22
    - android-25
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
jdk: oraclejdk8

script:
    ./gradlew build connectedCheck
    
    
